name: Daily Commit

on:
  schedule:
    - cron: '0 9 * * *'  # Runs once a day at 9:00 AM UTC

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add commit with email 23f2003893@ds.study.iitm.ac.in
        run: |
          # Create a file with the current date and time, ensuring it changes each time
          echo "Commit made at $(date)" > timestamp_$(date +%Y-%m-%d_%H-%M-%S).txt
          git config --global user.email "23f2003893@ds.study.iitm.ac.in"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Daily commit by GitHub Actions"
          git push


