name: Python CI Workflow

# Trigger the workflow on specific events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run
jobs:
  test:
    runs-on: ubuntu-latest  # Use a virtual machine

    steps:
      # Checkout the code
      - name: 23f2003893@ds.study.iitm.ac.in
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests or scripts
      - name: Run tests
        run: python your_script.py
